### ISSUE TITLE
ZFS 2.0.6 available for 6.10.0-rc2e/f/g but not ZFS 2.1.1

### ISSUE THREAD

**Issue by ajgnet** [Steini1984/unRAID6-ZFS#4]
When upgrading to 6.10.0-rc2g, ZFS downgrades from 2.1.1 to 2.0.6.

**Comment by ich777** [comment]
Please use the unRAID forums for reporting such problems.
Already answered here:
https://forums.unraid.net/topic/41333-zfs-plugin-for-unraid/?do=findComment&comment=1044055

Also keep in mind that 6.10.0rc2e/f/g is not realeased to the public yet, anyways thank you for the report.
